<script lang="ts">
	import type { StoryCard, StoryCardCut, StoryCardReference } from './storycard';
	import type { VideoPackage } from '../../core/videoPackageCore';
	import { resolveVideoProductionImageReference, storeVideoProductionImage } from '$lib/videoProductionStorage';

	let {
		card,
		thumbnailUrl = '',
		conversationSummary = '',
		motionPrompt = '',
		videoPackage = null,
		referenceImages = [],
		disabled = false,
		onMotionPromptChange,
		onReferenceImagesChange,
		onGenerateImage,
		onGenerateVideo,
		onGenerateComic,
		onSaveJson,
	}: {
		card: StoryCard;
		thumbnailUrl?: string;
		conversationSummary?: string;
		motionPrompt?: string;
		videoPackage?: VideoPackage | null;
		referenceImages?: string[];
		defaultOpen?: boolean;
		disabled?: boolean;
		onMotionPromptChange?: (value: string) => void;
		onReferenceImagesChange?: (images: string[]) => void;
		onGenerateImage?: (card: StoryCard) => void;
		onGenerateVideo?: (videoPackage: VideoPackage) => void;
		onGenerateComic?: (card: StoryCard) => void;
		onEdit?: (card: StoryCard) => void;
		onSaveJson?: (card: StoryCard) => Promise<void> | void;
	} = $props();

	type CutRow = {
		cut: StoryCardCut;
		label: string;
		title: string;
		time: string;
		description: string;
		requiredUnits: string[];
		characters: string;
		action: string;
		motion: string;
		dialogue: string;
		duration: number;
		expression: string;
		camera: string;
	};

	let editing = $state(false);
	let activeTab = $state<'story' | 'package' | 'motion'>('story');
	let saving = $state(false);
	let referenceSaving = $state(false);
	let editError = $state('');
	let referenceError = $state('');
	let draggedIndex = $state<number | null>(null);
	let draggedReferenceIndex = $state<number | null>(null);
	let draft = $state<StoryCard | null>(null);
	let referenceDraft = $state<StoryCardReference[] | null>(null);
	let referenceDraftSourceKey = $state('');
	let referenceFileInput = $state<HTMLInputElement>();
	let referenceUrl = $state('');
	let referenceKind = $state<'Character REF' | '画像' | 'アニメシート' | '構造図'>('画像');

	const referenceThumbnail = $derived(
		card.parseSuccess === false
			? (referenceImages[0] ?? '')
			: (card.references.find((reference) => reference.kind === 'image' && reference.url)?.url ?? ''),
	);
	const thumbnail = $derived(thumbnailUrl || referenceThumbnail);
	const cutCount = $derived(card.cuts.length);
	const durationLabel = $derived(card.duration > 0 ? `${card.duration}秒` : '未設定');
	const themeLabel = $derived(card.theme || '未設定');
	const cutRows = $derived(buildCutRows(card));
	const referenceCard = $derived(referenceDraft
		? { ...card, references: referenceDraft }
		: card.parseSuccess === false
			? {
				...card,
				references: referenceImages.map((url, index) => ({
					id: `reference-${index + 1}`,
					kind: 'image' as const,
					title: `REF ${String(index + 1).padStart(2, '0')}`,
					url,
				})),
			}
			: card);
	const visibleReferenceItems = $derived(storyCardReferenceItems(referenceCard, referenceImages));
	const visibleReferences = $derived(visibleReferenceItems.map((reference) => reference.url).filter(Boolean));
	const shortSummary = $derived(card.parseSuccess === false ? '' : (card.summary.trim() || conversationSummary.trim() || card.theme.trim()));
	const generatorLabel = $derived(card.isFallback
		? 'Generated by Fallback'
		: `Generated by ${card.sourceModel?.toLowerCase() === 'gpt-5.5' ? 'GPT-5.5' : (card.sourceModel || 'GPT-5.5')}`);

	$effect(() => {
		console.log('[STORYCARD_CARD_DEBUG_RENDER]', {
			storyCard: card,
			motionPrompt,
			referenceImages,
			referenceCount: referenceImages.length,
		});
	});

	$effect(() => {
		const sourceKey = `${card.id}:${card.updatedAt}:${(card.references ?? []).map((reference) => `${reference.id}:${reference.url ?? ''}`).join('|')}:${referenceImages.join('|')}`;
		if (!referenceSaving && sourceKey !== referenceDraftSourceKey) {
			referenceDraft = null;
			referenceDraftSourceKey = sourceKey;
		}
	});

	function updateMotionPrompt(event: Event): void {
		onMotionPromptChange?.((event.currentTarget as HTMLTextAreaElement).value);
	}

	function referenceTitle(image: string, index: number): string {
		const reference = card.references.find((item) => item.url === image || item.id === image);
		return reference?.title?.trim() || reference?.id || `REF ${String(index + 1).padStart(2, '0')}`;
	}

	function storyCardReferenceItems(cardData: StoryCard, fallbackImages: string[]): Array<StoryCardReference & { url: string }> {
		const fromCard = (cardData.references ?? [])
			.filter((reference) => reference.url || reference.id)
			.map((reference, index) => ({
				...reference,
				id: reference.id || `reference-${index + 1}`,
				url: reference.url || reference.id,
			}));
		if (fromCard.length > 0) return fromCard;
		return fallbackImages.filter(Boolean).map((image, index) => ({
			id: `reference-${index + 1}`,
			kind: 'image',
			title: `REF ${String(index + 1).padStart(2, '0')}`,
			url: image,
			tags: ['画像'],
		}));
	}

	function currentReferenceItems(): StoryCardReference[] {
		return storyCardReferenceItems(referenceCard, referenceImages).map((reference, index) => ({
			id: reference.id || `reference-${index + 1}`,
			kind: reference.kind ?? 'image',
			title: reference.title,
			url: reference.url || reference.id,
			summary: reference.summary,
			tags: reference.tags ?? [],
		}));
	}

	function referenceKey(reference: StoryCardReference & { url: string }, index: number): string {
		return `${reference.id}:${reference.url}:${index}`;
	}

	function uniqueReferenceUrl(url: string): boolean {
		return !currentReferenceItems().some((reference) => reference.url === url || reference.id === url);
	}

	function referenceKindToStoryCardKind(kind: typeof referenceKind): StoryCardReference['kind'] {
		return kind === 'Character REF' ? 'character' : 'image';
	}

	function createReference(url: string, kind: typeof referenceKind, title: string = kind): StoryCardReference {
		return {
			id: `reference-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
			kind: referenceKindToStoryCardKind(kind),
			title,
			url,
			tags: [kind],
		};
	}

	async function saveReferenceCard(nextCard: StoryCard): Promise<void> {
		referenceSaving = true;
		referenceError = '';
		try {
			const nextImages = storyCardReferenceItems(nextCard, []).map((reference) => reference.url);
			onReferenceImagesChange?.(nextImages);
			console.log('[STORYCARD_REFERENCE_SAVE_START]', {
				storyCardId: nextCard.id,
				referenceCount: nextCard.references?.length ?? 0,
				references: (nextCard.references ?? []).map((reference) => ({
					id: reference.id,
					url: reference.url,
					title: reference.title,
				})),
			});
			if (nextCard.parseSuccess !== false) {
				await onSaveJson?.({ ...nextCard, updatedAt: new Date().toISOString() });
			}
			console.log('[STORYCARD_REFERENCE_SAVE_DONE]', {
				storyCardId: nextCard.id,
				referenceCount: nextCard.references?.length ?? 0,
			});
		} catch (error) {
			referenceError = error instanceof Error ? error.message : String(error);
			console.error('[STORYCARD_REFERENCE_SAVE_ERROR]', {
				storyCardId: nextCard.id,
				error,
				referenceCount: nextCard.references?.length ?? 0,
			});
		} finally {
			referenceSaving = false;
		}
	}

	async function addReferenceUrl(): Promise<void> {
		const url = referenceUrl.trim();
		if (!url || !uniqueReferenceUrl(url)) return;
		referenceUrl = '';
		const nextReferences = [...currentReferenceItems(), createReference(url, referenceKind)];
		referenceDraft = nextReferences;
		const nextCard = {
			...card,
			references: nextReferences,
		};
		await saveReferenceCard(nextCard);
	}

	async function addReferenceFiles(event: Event): Promise<void> {
		const input = event.currentTarget as HTMLInputElement;
		const files = Array.from(input.files ?? []).filter((file) => file.type.startsWith('image/'));
		input.value = '';
		const additions: StoryCardReference[] = [];
		for (const file of files) {
			const dataUrl = await new Promise<string>((resolve, reject) => {
				const reader = new FileReader();
				reader.onload = () => resolve(typeof reader.result === 'string' ? reader.result : '');
				reader.onerror = () => reject(reader.error ?? new Error(`Unable to read ${file.name}`));
				reader.readAsDataURL(file);
			});
			const mediaId = storeVideoProductionImage(dataUrl, `${referenceKind}: ${file.name}`);
			if (uniqueReferenceUrl(mediaId) && !additions.some((reference) => reference.url === mediaId)) {
				additions.push(createReference(mediaId, referenceKind, file.name));
			}
		}
		if (additions.length === 0) return;
		const nextReferences = [...currentReferenceItems(), ...additions];
		referenceDraft = nextReferences;
		await saveReferenceCard({ ...card, references: nextReferences });
	}

	async function deleteReference(referenceId: string): Promise<void> {
		const before = currentReferenceItems();
		const target = before.find((reference) => reference.id === referenceId);
		const nextReferences = before.filter((reference) => reference.id !== referenceId);
		console.log('[STORYCARD_REFERENCE_DELETE_CLICK]', {
			storyCardId: card.id,
			referenceId,
			targetUrl: target?.url,
			cardReferenceCount: card.references?.length ?? 0,
			fallbackReferenceCount: referenceImages.length,
			beforeCount: before.length,
			afterCount: nextReferences.length,
		});
		referenceDraft = nextReferences;
		console.log('[STORYCARD_REFERENCE_DELETE_LOCAL_STATE]', {
			storyCardId: card.id,
			referenceId,
			localReferenceCount: referenceDraft.length,
			stillPresent: referenceDraft.some((reference) => reference.id === referenceId),
		});
		await saveReferenceCard({ ...card, references: nextReferences });
	}

	async function moveReference(from: number, to: number): Promise<void> {
		const references = currentReferenceItems();
		if (from === to || from < 0 || to < 0 || from >= references.length || to >= references.length) return;
		const [item] = references.splice(from, 1);
		references.splice(to, 0, item);
		referenceDraft = references;
		console.log('[STORYCARD_REFERENCE_MOVE]', {
			storyCardId: card.id,
			from,
			to,
			referenceCount: references.length,
		});
		await saveReferenceCard({ ...card, references });
	}

	function onReferenceDragStart(index: number): void {
		draggedReferenceIndex = index;
	}

	async function onDropReference(index: number): Promise<void> {
		if (draggedReferenceIndex === null) return;
		const from = draggedReferenceIndex;
		draggedReferenceIndex = null;
		await moveReference(from, index);
	}

	function cloneCard(value: StoryCard): StoryCard {
		return JSON.parse(JSON.stringify(value)) as StoryCard;
	}

	function compact(value: string | undefined, fallback = '未設定'): string {
		const text = (value ?? '').replace(/\s+/g, ' ').trim();
		if (!text) return fallback;
		return text.length > 34 ? `${text.slice(0, 34)}...` : text;
	}

	function formatTime(seconds: number): string {
		const safe = Math.max(0, Math.round(seconds));
		const minutes = Math.floor(safe / 60);
		const rest = safe % 60;
		return `${minutes}:${rest.toString().padStart(2, '0')}`;
	}

	function cutDuration(cardData: StoryCard, cut: StoryCardCut): number {
		if (typeof cut.duration === 'number' && cut.duration > 0) return cut.duration;
		if (cardData.duration > 0 && cardData.cuts.length > 0) return cardData.duration / cardData.cuts.length;
		return 3;
	}

	function buildCutRows(cardData: StoryCard): CutRow[] {
		let cursor = 0;
		return cardData.cuts.map((cut, index) => {
			const length = cutDuration(cardData, cut);
			const start = cursor;
			const end = cursor + length;
			cursor = end;
			return {
				cut,
				label: `SCENE${String(index + 1).padStart(2, '0')}`,
				title: compact(cut.title || cut.summary, `Cut ${index + 1}`),
				time: compact(cut.time || `${formatTime(start)}〜${formatTime(end)}`, ''),
				description: compact(cut.description || cut.summary, '説明未設定'),
				requiredUnits: cut.requiredUnits ?? cut.characters ?? [],
				characters: compact(cut.characters?.join('・') || cardData.characters.map((item) => item.name).join('・')),
				action: compact(cut.action || cut.summary),
				motion: cut.motion || cut.action || cut.description || cut.summary || '未設定',
				dialogue: cut.dialogue || '（台詞なし）',
				duration: length,
				expression: compact(cut.emotion || cardData.emotion),
				camera: compact(cut.camera),
			};
		});
	}

	function reindexCuts(cuts: StoryCardCut[]): StoryCardCut[] {
		return cuts.map((cut, index) => ({
			...cut,
			order: index + 1,
			id: cut.id || `cut-${Date.now()}-${index}`,
			summary: cut.summary || cut.action || cut.title || `CUT${String(index + 1).padStart(2, '0')}`,
		}));
	}

	function startEdit(): void {
		activeTab = 'story';
		draft = cloneCard(card);
		editError = '';
		draggedIndex = null;
		editing = true;
	}

	function cancelEdit(): void {
		editing = false;
		draft = null;
		editError = '';
		draggedIndex = null;
	}

	function addCut(): void {
		if (!draft) return;
		const nextOrder = draft.cuts.length + 1;
		draft.cuts = reindexCuts([
			...draft.cuts,
			{
				id: `cut-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`,
				order: nextOrder,
				time: '',
				title: `CUT${String(nextOrder).padStart(2, '0')}`,
				summary: '',
				characters: [],
				action: '',
				emotion: '',
				camera: '',
			},
		]);
	}

	function deleteCut(index: number): void {
		if (!draft) return;
		draft.cuts = reindexCuts(draft.cuts.filter((_, cutIndex) => cutIndex !== index));
	}

	function moveCut(from: number, to: number): void {
		if (!draft || from === to || from < 0 || to < 0 || from >= draft.cuts.length || to >= draft.cuts.length) return;
		const cuts = [...draft.cuts];
		const [item] = cuts.splice(from, 1);
		cuts.splice(to, 0, item);
		draft.cuts = reindexCuts(cuts);
	}

	function onDragStart(index: number): void {
		draggedIndex = index;
	}

	function onDropCut(index: number): void {
		if (draggedIndex === null) return;
		moveCut(draggedIndex, index);
		draggedIndex = null;
	}

	function updateRequiredUnits(index: number, value: string): void {
		if (!draft?.cuts[index]) return;
		draft.cuts[index].requiredUnits = value.split(/[、,\n]/).map((item) => item.trim()).filter(Boolean).slice(0, 16);
	}

	function syncCutSummary(cut: StoryCardCut): StoryCardCut {
		return {
			...cut,
			time: cut.start && cut.end ? `${cut.start}-${cut.end}` : cut.time,
			summary: (cut.description || cut.summary || cut.title || '').slice(0, 180),
			action: cut.description || cut.action,
			characters: cut.requiredUnits ?? cut.characters,
		};
	}

	async function saveEdit(): Promise<void> {
		if (!draft) return;
		editError = '';
		if (!draft.title.trim()) {
			editError = 'タイトルを入力してください。';
			return;
		}
		if (!draft.theme.trim()) {
			editError = 'テーマを入力してください。';
			return;
		}
		saving = true;
		try {
			const next: StoryCard = {
				...draft,
				duration: Math.max(0, Number(draft.duration) || 0),
				cuts: reindexCuts(draft.cuts.map(syncCutSummary)),
				updatedAt: new Date().toISOString(),
			};
			await onSaveJson?.(next);
			editing = false;
			draft = null;
		} catch (error) {
			editError = error instanceof Error ? error.message : String(error);
		} finally {
			saving = false;
		}
	}
</script>

<article class="storycard-card" aria-label={`Animation Project: ${card.title}`}>
	{#if shortSummary}
		<p class="shiro-summary"><strong>{card.characters[0]?.name || 'Character'}</strong><span>{shortSummary}</span></p>
	{/if}
	<div class="storycard-top">
		{#if thumbnail}
			<img class="storycard-thumb" src={thumbnail} alt={`${card.title} thumbnail`} />
		{:else}
			<div class="storycard-thumb storycard-thumb-empty" aria-hidden="true"><span>AS</span></div>
		{/if}

		<div class="storycard-main">
			<div class="storycard-kicker-row">
				<div class="storycard-kicker">Animation Project</div>
				<span class:fallback={card.isFallback} class="generator-badge">{generatorLabel}</span>
			</div>
			<h3>{card.title}</h3>
			<div class="storycard-meta" aria-label="StoryCard summary">
				<span>{durationLabel}</span>
				<span>SCENE {cutCount}</span>
				<span>{themeLabel}</span>
			</div>
		</div>
	</div>

	{#if card.generationError}
		<section class="storycard-generation-error" aria-label="StoryCard Raw Response">
			<details open>
				<summary>Raw Response ({card.generationError.rawResponseLength} chars{card.generationError.rawResponseTruncated ? ' / UI表示は先頭7,000文字' : ''})</summary>
				<pre>{card.generationError.rawResponse || '(empty response)'}</pre>
			</details>
		</section>
	{/if}

	<div class="storycard-tabs" role="tablist" aria-label="Animation Project">
		<button type="button" role="tab" aria-selected={activeTab === 'story'} class:active={activeTab === 'story'} onclick={() => activeTab = 'story'}>Scene Timeline</button>
		<button type="button" role="tab" aria-selected={activeTab === 'package'} class:active={activeTab === 'package'} onclick={() => activeTab = 'package'}>Animation Project</button>
		<button type="button" role="tab" aria-selected={activeTab === 'motion'} class:active={activeTab === 'motion'} onclick={() => activeTab = 'motion'}>Motion Prompt</button>
	</div>

	<section class="storycard-tab-panel" role="tabpanel">
	{#if activeTab === 'story'}
	{#if cutRows.length > 0}
		<div class="cut-list storyboard-first" aria-label="StoryCard scenes">
			{#each cutRows as row (row.cut.id)}
				<article class="cut-item storyboard-cut">
					<header>
						<span class="cut-name">{row.label} {row.title}</span>
						<span class="cut-time">{row.time}</span>
					</header>
					<p>{row.description}</p>
					<dl class="scene-fields">
						<div><dt>duration</dt><dd>{row.duration}s</dd></div>
						<div><dt>camera</dt><dd>{row.camera}</dd></div>
						<div><dt>motion</dt><dd>{row.motion}</dd></div>
						<div><dt>dialogue</dt><dd>{row.dialogue}</dd></div>
					</dl>
					{#if row.requiredUnits.length > 0}
						<div class="required-units" aria-label="Required units">
							{#each row.requiredUnits as unit (unit)}<span>{unit}</span>{/each}
						</div>
					{/if}
				</article>
			{/each}
		</div>
	{:else}
		<p class="empty-scenes">構造化Sceneがありません。</p>
	{/if}

	{#if editing && draft}
		<section class="storycard-editor" aria-label="StoryCard editor">
			<div class="editor-grid">
				<label>
					<span>タイトル</span>
					<input bind:value={draft.title} />
				</label>
				<label>
					<span>テーマ</span>
					<input bind:value={draft.theme} />
				</label>
				<label>
					<span>尺 秒</span>
					<input type="number" min="0" step="1" bind:value={draft.duration} />
				</label>
			</div>

			<div class="editor-head">
				<strong>CUT編集</strong>
				<button type="button" onclick={addCut}>CUTを追加</button>
			</div>

			<div class="edit-cut-list">
				{#each draft.cuts as cut, index (cut.id)}
					<section
						class="edit-cut"
						role="listitem"
						draggable="true"
						ondragstart={() => onDragStart(index)}
						ondragover={(event) => event.preventDefault()}
						ondrop={() => onDropCut(index)}
					>
						<div class="edit-cut-head">
							<span>CUT{String(index + 1).padStart(2, '0')}</span>
							<div>
								<button type="button" onclick={() => moveCut(index, index - 1)} disabled={index === 0}>上へ</button>
								<button type="button" onclick={() => moveCut(index, index + 1)} disabled={index === draft.cuts.length - 1}>下へ</button>
								<button type="button" class="danger" onclick={() => deleteCut(index)}>削除</button>
							</div>
						</div>
						<div class="cut-edit-grid">
							<label><span>開始</span><input bind:value={cut.start} placeholder="0:00" /></label>
							<label><span>終了</span><input bind:value={cut.end} placeholder="0:04" /></label>
							<label><span>見出し</span><input bind:value={cut.title} /></label>
							<label><span>説明</span><input bind:value={cut.description} /></label>
							<label><span>必須ユニット</span><input value={(cut.requiredUnits ?? []).join('、')} oninput={(event) => updateRequiredUnits(index, event.currentTarget.value)} /></label>
						</div>
					</section>
				{/each}
			</div>

			{#if editError}<div class="json-error">{editError}</div>{/if}
			<div class="json-actions">
				<button type="button" disabled={saving} onclick={cancelEdit}>キャンセル</button>
				<button type="button" disabled={saving} onclick={saveEdit}>{saving ? '保存中...' : '保存'}</button>
			</div>
		</section>
	{/if}

		<div class="storycard-secondary-actions" aria-label="StoryCard actions">
			<button type="button" disabled={disabled} onclick={startEdit}>編集</button>
			<button type="button" disabled={disabled} onclick={() => onGenerateImage?.(card)}>画像生成</button>
			<button type="button" disabled={disabled} onclick={() => onGenerateComic?.(card)}>漫画生成</button>
		</div>
	{:else if activeTab === 'package'}
		<div class="video-package-panel">
			{#if videoPackage}
				<div class="video-package-meta">
					<span>{videoPackage.duration}s</span>
					<span>{videoPackage.scenes.length} SCENE</span>
					<span>Source: {videoPackage.source_storycard_id}</span>
				</div>
				<pre>{JSON.stringify(videoPackage, null, 2)}</pre>
			{:else}
				<p>Animation Projectはまだ生成されていません。</p>
			{/if}
			<details>
				<summary>Legacy StoryCard data</summary>
				<pre>{JSON.stringify(card, null, 2)}</pre>
			</details>
		</div>
	{:else if activeTab === 'motion'}
		<div class="motion-panel">
			<details>
				<summary>内部データを展開</summary>
				<label for={`storycard-motion-tab-${card.id}`}>Motion Prompt</label>
				<textarea id={`storycard-motion-tab-${card.id}`} value={motionPrompt} oninput={updateMotionPrompt} disabled={disabled}></textarea>
			</details>
		</div>
		{:else}
			<div class="reference-panel">
				<div class="reference-toolbar">
					<label>
						<span>追加カテゴリ</span>
						<select bind:value={referenceKind} disabled={disabled || referenceSaving}>
							<option value="Character REF">Character REF</option>
							<option value="画像">画像</option>
							<option value="アニメシート">アニメシート</option>
							<option value="構造図">構造図</option>
						</select>
					</label>
					<label class="reference-url-input">
						<span>画像URL / media ID</span>
						<input bind:value={referenceUrl} placeholder="/api/... または image-..." disabled={disabled || referenceSaving} />
					</label>
					<button type="button" onclick={addReferenceUrl} disabled={disabled || referenceSaving || !referenceUrl.trim()}>参照画像を追加</button>
					<input bind:this={referenceFileInput} type="file" accept="image/*" multiple hidden onchange={addReferenceFiles} />
					<button type="button" onclick={() => referenceFileInput?.click()} disabled={disabled || referenceSaving}>画像ファイルを追加</button>
				</div>
				{#if referenceError}<div class="json-error">{referenceError}</div>{/if}
				{#if visibleReferenceItems.length > 0}
					<div class="reference-grid">
							{#each visibleReferenceItems as reference, index (referenceKey(reference, index))}
							<figure
									draggable={!disabled && !referenceSaving && visibleReferenceItems.length > 1}
								ondragstart={() => onReferenceDragStart(index)}
								ondragover={(event) => event.preventDefault()}
								ondrop={() => void onDropReference(index)}
							>
								<img src={resolveVideoProductionImageReference(reference.url)} alt={`参照画像 ${index + 1}`} />
								<div class="reference-card-actions">
									<button type="button" onclick={() => moveReference(index, index - 1)} disabled={disabled || referenceSaving || index === 0}>↑</button>
									<button type="button" onclick={() => moveReference(index, index + 1)} disabled={disabled || referenceSaving || index === visibleReferenceItems.length - 1}>↓</button>
									<button type="button" class="danger" onclick={() => deleteReference(reference.id)} disabled={disabled || referenceSaving}>削除</button>
								</div>
								{#if reference.tags?.length}
									<div class="reference-tags">{#each reference.tags as tag}<span>{tag}</span>{/each}</div>
								{/if}
								<figcaption>{reference.title || referenceTitle(reference.url, index)}</figcaption>
							</figure>
						{/each}
					</div>
				{:else}
					<p class="empty-reference">参照画像はありません。</p>
				{/if}
				{#if false && visibleReferences.length > 0}
				<div class="reference-grid">
					{#each visibleReferences as image, index (image)}
						<figure>
							<img src={image} alt={`参照画像 ${index + 1}`} />
							<figcaption>{referenceTitle(image, index)}</figcaption>
						</figure>
					{/each}
				</div>
			{:else if false}
				<p class="empty-reference">参照画像はありません。</p>
			{/if}
		</div>
	{/if}
	</section>

	<button class="generate-video" type="button" disabled={disabled || !videoPackage || !motionPrompt.trim()} onclick={() => videoPackage && onGenerateVideo?.(videoPackage)}>動画生成</button>
</article>

<style>
	.storycard-card { display: grid; gap: 10px; overflow: hidden; border: 1px solid rgba(34, 211, 238, 0.28); border-radius: 8px; background: rgba(15, 23, 42, 0.76); box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.04); }
	.storycard-generation-error { display: grid; gap: 5px; margin: 0 12px; padding: 10px; border: 1px solid rgba(248, 113, 113, .42); border-radius: 7px; background: rgba(127, 29, 29, .18); color: #fecaca; }
	.storycard-generation-error summary { cursor: pointer; color: #fda4af; font-size: 12px; font-weight: 800; }
	.storycard-generation-error pre { max-height: 280px; margin: 7px 0 0; padding: 9px; overflow: auto; border-radius: 5px; background: rgba(2, 6, 23, .82); color: #e2e8f0; font: 11px/1.5 ui-monospace, monospace; white-space: pre-wrap; overflow-wrap: anywhere; }
	.shiro-summary { display: grid; grid-template-columns: max-content minmax(0, 1fr); gap: 9px; margin: 0; padding: 11px 12px; border-bottom: 1px solid rgba(125, 211, 252, 0.16); background: rgba(8, 47, 73, 0.22); color: #e0f2fe; font-size: 13px; line-height: 1.55; }
	.shiro-summary strong { color: #67e8f9; }
	.storycard-top { display: grid; grid-template-columns: 96px minmax(0, 1fr); gap: 12px; align-items: center; padding: 12px 12px 0; }
	.storycard-thumb { width: 96px; aspect-ratio: 16 / 10; object-fit: cover; border: 1px solid rgba(125, 211, 252, 0.28); border-radius: 6px; background: #020617; }
	.storycard-thumb-empty { display: grid; place-items: center; color: #67e8f9; font-size: 18px; font-weight: 900; }
	.storycard-main { min-width: 0; display: grid; gap: 7px; }
	.storycard-kicker-row { display: flex; flex-wrap: wrap; align-items: center; justify-content: space-between; gap: 8px; }
	.storycard-kicker { color: #67e8f9; font-size: 12px; font-weight: 900; letter-spacing: 0; }
	.generator-badge { padding: 3px 7px; border: 1px solid rgba(74, 222, 128, 0.38); border-radius: 999px; background: rgba(22, 101, 52, 0.2); color: #86efac; font-size: 10px; font-weight: 900; }
	.generator-badge.fallback { border-color: rgba(251, 191, 36, 0.42); background: rgba(120, 53, 15, 0.24); color: #fde68a; }
	h3 { margin: 0; color: #f8fafc; font-size: 18px; line-height: 1.35; overflow-wrap: anywhere; }
	.storycard-meta { display: flex; flex-wrap: wrap; gap: 6px; }
	.storycard-meta span { max-width: 100%; padding: 4px 8px; border: 1px solid rgba(125, 211, 252, 0.24); border-radius: 6px; background: rgba(14, 116, 144, 0.16); color: #dbeafe; font-size: 12px; font-weight: 800; overflow-wrap: anywhere; }
	.storycard-tabs { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); margin-top: 2px; padding: 0 12px; border-bottom: 1px solid rgba(125, 211, 252, 0.2); }
	.storycard-tabs button { min-width: 0; border: 0; border-bottom: 2px solid transparent; border-radius: 0; background: transparent; color: #94a3b8; white-space: normal; }
	.storycard-tabs button.active { border-bottom-color: #22d3ee; color: #ecfeff; background: rgba(8, 145, 178, 0.12); }
	.storycard-tab-panel { display: grid; gap: 10px; min-height: 132px; }
	.cut-list { display: grid; gap: 6px; padding: 0 12px; }
	.storyboard-first { padding-top: 12px; }
	.cut-item { border: 1px solid rgba(125, 211, 252, 0.18); border-radius: 6px; background: rgba(2, 6, 23, 0.26); color: #dbeafe; }
	.storyboard-cut { display: grid; gap: 8px; padding: 10px; }
	.storyboard-cut header { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 10px; align-items: center; }
	.storyboard-cut p { margin: 0; color: #dbeafe; font-size: 13px; line-height: 1.55; }
	.scene-fields { display: grid; gap: 5px; margin: 0; }
	.scene-fields div { display: grid; grid-template-columns: 72px minmax(0, 1fr); gap: 8px; align-items: start; }
	.scene-fields dt { color: #67e8f9; font: 700 11px/1.5 ui-monospace, monospace; }
	.scene-fields dd { margin: 0; color: #e2e8f0; font-size: 12px; line-height: 1.5; overflow-wrap: anywhere; white-space: pre-wrap; }
	.empty-scenes { margin: 0 12px; padding: 10px; border: 1px solid rgba(248, 113, 113, .28); border-radius: 6px; color: #fca5a5; }
	.required-units { display: flex; flex-wrap: wrap; gap: 5px; }
	.required-units span { padding: 3px 7px; border: 1px solid rgba(167, 139, 250, 0.3); border-radius: 999px; background: rgba(76, 29, 149, 0.18); color: #ddd6fe; font-size: 10px; font-weight: 800; }
	.cut-name { min-width: 0; color: #f8fafc; font-size: 13px; font-weight: 900; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
	.cut-time { color: #93c5fd; font-size: 12px; font-weight: 800; white-space: nowrap; }
	.storycard-editor { display: grid; gap: 12px; margin: 0 12px; padding: 10px; border: 1px solid rgba(251, 191, 36, 0.24); border-radius: 6px; background: rgba(15, 23, 42, 0.92); }
	.editor-grid, .cut-edit-grid { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; }
	label { display: grid; gap: 4px; min-width: 0; }
	label span, .editor-head strong, .edit-cut-head span { color: #7dd3fc; font-size: 12px; font-weight: 900; }
	input { min-width: 0; box-sizing: border-box; border: 1px solid rgba(148, 163, 184, 0.28); border-radius: 6px; background: #020617; color: #e2e8f0; font: inherit; font-size: 13px; padding: 8px; }
	.editor-head, .edit-cut-head, .json-actions { display: flex; align-items: center; justify-content: space-between; gap: 8px; }
	.edit-cut-list { display: grid; gap: 8px; }
	.edit-cut { display: grid; gap: 8px; padding: 10px; border: 1px solid rgba(125, 211, 252, 0.2); border-radius: 6px; background: rgba(2, 6, 23, 0.32); }
	.edit-cut[draggable='true'] { cursor: grab; }
	.edit-cut-head div { display: flex; gap: 6px; flex-wrap: wrap; justify-content: flex-end; }
	.json-error { color: #fecaca; font-size: 12px; font-weight: 800; }
	.storycard-secondary-actions { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 8px; padding: 0 12px; }
	.motion-panel, .reference-panel, .video-package-panel { display: grid; gap: 7px; padding: 0 12px; }
	.video-package-panel pre { max-height: 320px; margin: 0; padding: 10px; overflow: auto; border: 1px solid rgba(167, 139, 250, 0.24); border-radius: 6px; background: #020617; color: #ddd6fe; font: 12px/1.5 ui-monospace, monospace; white-space: pre-wrap; }
	.video-package-panel p { margin: auto; color: #94a3b8; }
	.video-package-meta { display: flex; flex-wrap: wrap; gap: 6px; }
	.video-package-meta span { padding: 3px 7px; border: 1px solid rgba(167, 139, 250, 0.3); border-radius: 999px; color: #ddd6fe; font-size: 10px; }
	.motion-panel label { color: #7dd3fc; font-size: 12px; font-weight: 900; }
	.motion-panel textarea { width: 100%; min-height: 150px; box-sizing: border-box; resize: vertical; border: 1px solid rgba(125, 211, 252, 0.28); border-radius: 6px; padding: 10px; background: #020617; color: #f8fafc; font: 13px/1.55 ui-monospace, monospace; }
	.reference-toolbar { display: grid; grid-template-columns: minmax(120px, 160px) minmax(180px, 1fr) auto auto; gap: 8px; align-items: end; }
	.reference-toolbar label { margin: 0; }
	.reference-toolbar select { min-width: 0; box-sizing: border-box; border: 1px solid rgba(148, 163, 184, 0.28); border-radius: 6px; background: #020617; color: #e2e8f0; font: inherit; font-size: 13px; padding: 8px; }
	.reference-url-input { min-width: 0; }
	.reference-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(92px, 1fr)); gap: 8px; }
	.reference-grid figure { display: grid; gap: 5px; min-width: 0; margin: 0; padding: 7px; border: 1px solid rgba(125, 211, 252, 0.18); border-radius: 8px; background: rgba(2, 6, 23, 0.34); }
	.reference-grid figure[draggable='true'] { cursor: grab; }
	.reference-grid img { width: 100%; aspect-ratio: 1; object-fit: cover; border: 1px solid rgba(125, 211, 252, 0.26); border-radius: 6px; background: #020617; }
	.reference-grid figcaption { color: #7dd3fc; font-size: 10px; font-weight: 800; text-align: center; }
	.reference-card-actions { display: flex; gap: 4px; justify-content: center; }
	.reference-card-actions button { min-height: 26px; padding: 3px 6px; font-size: 10px; }
	.reference-tags { display: flex; flex-wrap: wrap; justify-content: center; gap: 4px; }
	.reference-tags span { padding: 2px 5px; border: 1px solid rgba(167, 139, 250, 0.28); border-radius: 999px; color: #ddd6fe; font-size: 9px; font-weight: 800; }
	.empty-reference { margin: auto; color: #94a3b8; font-size: 13px; }
	.generate-video { margin: 0 12px 12px; min-height: 42px; border-color: rgba(34, 211, 238, 0.58); background: rgba(8, 145, 178, 0.28); color: #ecfeff; font-size: 14px; }
	button { min-height: 34px; padding: 7px 8px; border: 1px solid rgba(125, 211, 252, 0.35); border-radius: 6px; background: rgba(14, 116, 144, 0.18); color: #e0f2fe; font: inherit; font-size: 12px; font-weight: 800; cursor: pointer; }
	button.danger { border-color: rgba(248, 113, 113, 0.45); color: #fecaca; background: rgba(127, 29, 29, 0.2); }
	button:disabled { cursor: not-allowed; opacity: 0.5; }
	@media (max-width: 720px) {
		.storycard-top { grid-template-columns: 78px minmax(0, 1fr); gap: 10px; }
		.storycard-thumb { width: 78px; }
		h3 { font-size: 16px; }
		.editor-grid, .cut-edit-grid { grid-template-columns: minmax(0, 1fr); }
		.storycard-tabs { padding: 0 8px; }
		.storycard-tabs button { padding-inline: 3px; font-size: 11px; }
		.storycard-secondary-actions { grid-template-columns: minmax(0, 1fr); }
		.reference-toolbar { grid-template-columns: minmax(0, 1fr); }
	}
</style>
